-- Auto Generated Script --
PRAGMA foreign_keys = ON;

PRAGMA journal_mode = WAL;

PRAGMA synchronous = NORMAL;

CREATE TABLE IF NOT EXISTS armies (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    isFavorite INTEGER CHECK(isFavorite IN (0,1)),
    totalPoints INTEGER,
    warlordId INTEGER,
    factionId INTEGER NOT NULL,
    detachmentId INTEGER,
    unitIdList TEXT,
    equippedRangedWeaponIdList TEXT,
    equippedMeleeWeaponIdList TEXT,
    FOREIGN KEY(factionId) REFERENCES factions(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(detachmentId) REFERENCES detachments(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS core_abilities (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ability TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS detachments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    factionId INTEGER NOT NULL,
    strategyId INTEGER,
    detachmentRule TEXT,
    FOREIGN KEY(factionId) REFERENCES factions(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS factions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS melee_weapons (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    A TEXT NOT NULL,
    WS INTEGER NOT NULL,
    S INTEGER NOT NULL,
    AP INTEGER NOT NULL,
    D TEXT NOT NULL,
    keywordIdList TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS other_abilities (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ability TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ranged_weapons (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    range INTEGER NOT NULL,
    A TEXT NOT NULL,
    BS INTEGER NOT NULL,
    S INTEGER NOT NULL,
    AP INTEGER NOT NULL,
    D TEXT NOT NULL,
    keywordIdList TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS unit_keywords (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    keyword TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS units (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    factionId INTEGER NOT NULL,
    name TEXT NOT NULL,
    points INTEGER NOT NULL CHECK(points >= 0),
    M INTEGER NOT NULL,
    T INTEGER NOT NULL,
    SV INTEGER NOT NULL,
    W INTEGER NOT NULL,
    LD INTEGER NOT NULL,
    OC INTEGER NOT NULL,
    invulnerableSave INTEGER NOT NULL,
    category INTEGER NOT NULL,
    composition TEXT NOT NULL,
    coreAbilityIdList TEXT NOT NULL,
    otherAbilityIdList TEXT NOT NULL,
    keywordIdList TEXT NOT NULL,
    rangedWeaponIdList TEXT NOT NULL,
    meleeWeaponIdList TEXT NOT NULL,
    FOREIGN KEY(factionId) REFERENCES factions(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS weapon_keywords (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    keyword TEXT NOT NULL
);

