package eecs2311.group2.wh40k_easycombat.service.editor;

import eecs2311.group2.wh40k_easycombat.model.editor.EditorRerollType;
import eecs2311.group2.wh40k_easycombat.model.editor.EditorRuleDefinition;

import java.util.ArrayList;
import java.util.List;

public class VisualVmScriptBuilder {

    public String build(EditorRuleDefinition rule) {
        EditorRuleDefinition safeRule = rule == null ? new EditorRuleDefinition() : rule;
        StringBuilder builder = new StringBuilder();

        builder.append("# Generated by the visual VM editor").append('\n');
        builder.append("0 -> hit_modifier").append('\n');
        builder.append("0 -> wound_modifier").append('\n');
        builder.append("0 -> attacks_modifier").append('\n');
        builder.append("0 -> damage_modifier").append('\n');
        builder.append("0 -> ap_modifier").append('\n');
        builder.append("0 -> hit_reroll").append('\n');
        builder.append("0 -> wound_reroll").append('\n');
        builder.append("\"\" -> extra_weapon_keywords").append('\n');

        List<String> conditions = buildConditions(safeRule);
        boolean hasEffects = hasAnyEffect(safeRule);
        if (!hasEffects) {
            builder.append('\n');
            builder.append("# No visual effect has been selected yet.");
            return builder.toString().trim();
        }

        builder.append('\n');
        String indent = "";
        if (!conditions.isEmpty()) {
            builder.append("if ").append(String.join(" && ", conditions)).append('\n');
            indent = "    ";
        }

        appendAdditive(builder, indent, "hit_modifier", safeRule.getVisualHitModifier());
        appendAdditive(builder, indent, "wound_modifier", safeRule.getVisualWoundModifier());
        appendAdditive(builder, indent, "attacks_modifier", safeRule.getVisualAttacksModifier());
        appendAdditive(builder, indent, "damage_modifier", safeRule.getVisualDamageModifier());
        appendAdditive(builder, indent, "ap_modifier", safeRule.getVisualApModifier());
        appendReroll(builder, indent, "hit_reroll", safeRule.getVisualHitReroll());
        appendReroll(builder, indent, "wound_reroll", safeRule.getVisualWoundReroll());
        appendKeywords(builder, indent, safeRule.getVisualExtraWeaponKeywords());

        if (!conditions.isEmpty()) {
            builder.append("endif").append('\n');
        }

        return builder.toString().trim();
    }

    private List<String> buildConditions(EditorRuleDefinition rule) {
        List<String> conditions = new ArrayList<>();

        if (rule.isVisualWithinHalfRange()) conditions.add("within_half_range");
        if (rule.isVisualRemainedStationary()) conditions.add("remained_stationary");
        if (rule.isVisualAdvancedThisTurn()) conditions.add("advanced_this_turn");
        if (rule.isVisualFellBackThisTurn()) conditions.add("fell_back_this_turn");
        if (rule.isVisualChargedThisTurn()) conditions.add("charged_this_turn");
        if (rule.isVisualAttackerCanFight()) conditions.add("attacker_can_fight");
        if (rule.isVisualTargetHasCover()) conditions.add("target_has_cover");
        if (rule.isVisualBlastIsLegal()) conditions.add("blast_is_legal");
        if (rule.isVisualTargetIsInfantry()) conditions.add("target_is_infantry");
        if (rule.isVisualTargetIsVehicle()) conditions.add("target_is_vehicle");
        if (rule.isVisualTargetIsMonster()) conditions.add("target_is_monster");
        if (rule.isVisualTargetIsCharacter()) conditions.add("target_is_character");
        if (rule.isVisualTargetIsPsyker()) conditions.add("target_is_psyker");

        return conditions;
    }

    private boolean hasAnyEffect(EditorRuleDefinition rule) {
        return rule.getVisualHitModifier() != 0
                || rule.getVisualWoundModifier() != 0
                || rule.getVisualAttacksModifier() != 0
                || rule.getVisualDamageModifier() != 0
                || rule.getVisualApModifier() != 0
                || rule.getVisualHitReroll() != EditorRerollType.NONE
                || rule.getVisualWoundReroll() != EditorRerollType.NONE
                || !safe(rule.getVisualExtraWeaponKeywords()).isBlank();
    }

    private void appendAdditive(StringBuilder builder, String indent, String variable, int delta) {
        if (delta == 0) {
            return;
        }
        if (delta > 0) {
            builder.append(indent).append(variable).append(" + ").append(delta).append(" -> ").append(variable).append('\n');
            return;
        }
        builder.append(indent).append(variable).append(" - ").append(Math.abs(delta)).append(" -> ").append(variable).append('\n');
    }

    private void appendReroll(StringBuilder builder, String indent, String variable, EditorRerollType rerollType) {
        EditorRerollType safeType = rerollType == null ? EditorRerollType.NONE : rerollType;
        if (safeType == EditorRerollType.NONE) {
            return;
        }

        int value = safeType == EditorRerollType.ONES ? 1 : 2;
        builder.append(indent).append(value).append(" -> ").append(variable).append('\n');
    }

    private void appendKeywords(StringBuilder builder, String indent, String rawKeywords) {
        String normalized = safe(rawKeywords);
        if (normalized.isBlank()) {
            return;
        }

        builder.append(indent)
                .append('"')
                .append(normalized.replace("\\", "\\\\").replace("\"", "\\\""))
                .append('"')
                .append(" -> extra_weapon_keywords")
                .append('\n');
    }

    private String safe(String value) {
        return value == null ? "" : value.trim();
    }
}
